# Heart Disease Prediction

References:

    [1] https://www.kaggle.com/ronitf/heart-disease-uci
    [2] "Statistics and Machine Learning in Python"; Edouard Duchesnay, Tommy Löfstedt, Feki Younes; Oct 2020.

In [1]:
import pandas as pd
from pandas import read_csv
import numpy as np
import sklearn.linear_model as lm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
filename = 'heart.csv'
df = read_csv(filename)

In [3]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [6]:
heart_data = df.values

In [8]:
X = heart_data[:, 0:12]
Y = heart_data[:, 13]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaled_X = scaler.fit_transform(X)

In [13]:
my_test_size = 0.2
seed = 2 
X_train, X_test, Y_train, Y_test = train_test_split(rescaled_X, Y, test_size = my_test_size , random_state = seed)

In [22]:
logreg = lm.LogisticRegression(C = 1e8, solver = 'lbfgs')

In [23]:
logreg.fit(X_train, Y_train)
Y_pred_logreg = logreg.predict(X_test)
errors = Y_pred_logreg != Y_test
print("Nb errors=%i, error rate=%.2f" % (errors.sum(), errors.sum() / len(Y_pred_logreg)))
print(logreg.coef_)

Nb errors=6, error rate=0.10
[[-0.01168827 -2.09716405  2.62602057 -1.92180159 -2.79311849  0.15877505
   0.92745569  2.57479132 -0.96661923 -2.43750436  1.52778537 -2.99106561]]

In [27]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
lda.fit(X_train, Y_train)
Y_pred_lda = lda.predict(X_test)
errors = Y_pred_lda != Y_test
print("Nb errors=%i, error rate=%.2f" % (errors.sum(), errors.sum() / len(Y_pred_lda)))
print(lda.coef_)

Nb errors=7, error rate=0.11
[[-0.04142091 -1.91448882  2.85141154 -1.45817633 -2.25107859  0.06373096
   0.86728578  2.6655741  -1.14411236 -2.58818554  1.59547631 -3.29071163]]

In [30]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
qda = QDA()
qda.fit(X_train, Y_train)
Y_pred_qda = qda.predict(X_test)
errors = Y_pred_qda != Y_test
print("Nb errors=%i, error rate=%.2f" % (errors.sum(), errors.sum() / len(Y_pred_qda)))

Nb errors=9, error rate=0.15